# Generated by Django 5.1.6 on 2025-03-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beaux',
            fields=[
                ('id_beaux', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('vendu', 'Vendu')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id_locataire', models.AutoField(primary_key=True, serialize=False)),
                ('pieces', models.IntegerField()),
                ('type', models.CharField(choices=[('locataire', 'Locataire'), ('acheteur', 'Acheteur')], max_length=20)),
                ('adresse1', models.TextField()),
                ('adresse2', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id_propriete', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_beaux', models.CharField(choices=[('terrain', 'Terrain'), ('immeuble', 'Immeuble'), ('appartement', 'Appartement')], max_length=20)),
                ('date_aquisition', models.DateField()),
                ('categorie', models.CharField(choices=[('location', 'Location'), ('vente', 'Vente'), ('mixte', 'Mixte')], max_length=20)),
                ('localisation', models.TextField()),
                ('coordonnees_gps', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage', models.CharField(choices=[('residentiel', 'Résidentiel'), ('commercial', 'Commercial'), ('mixte', 'Mixte')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('pieces', models.IntegerField()),
                ('mode', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=20)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('date_derniere_paiement', models.DateField()),
                ('id_beaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.beaux')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id_depense', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('id_propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.propriete')),
            ],
        ),
        migrations.AddField(
            model_name='beaux',
            name='id_propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.propriete'),
        ),
    ]
