# Generated by Django 5.1.4 on 2025-03-04 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestion_immobiliere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('type_document', models.CharField(choices=[('photo', 'Photo'), ('contrat', 'Contrat'), ('facture', 'Facture'), ('autre', 'Autre')], max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire')], max_length=20)),
                ('numero_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('recu_genere', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion_immobiliere.location')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
