# Generated by Django 5.1.4 on 2025-04-01 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0002_document_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_signature',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='type_operation',
            field=models.CharField(choices=[('location', 'Location'), ('vente', 'Vente')], default='location', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='pieces',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='prix_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
