# Generated by Django 5.1.4 on 2025-04-02 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0004_location_id_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locataire',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='locataire',
            name='adresse_employeur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='civilite',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M', max_length=4),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_validite_piece',
            field=models.DateField(blank=True, null=True, verbose_name="Date de validité de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='locataire',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locataire',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='locataire',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='locataire',
            name='nom_employeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='locataire',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='pieces_identite/%Y/%m/', verbose_name="Pièce d'identité"),
        ),
        migrations.AddField(
            model_name='locataire',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='locataire',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locataire',
            name='revenu_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='telephone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone secondaire'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='telephone_employeur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='adresse1',
            field=models.TextField(default='', verbose_name='Adresse actuelle'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='adresse2',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse complémentaire'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='pieces',
            field=models.IntegerField(default=1, verbose_name='Nombre de pièces souhaitées'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='type',
            field=models.CharField(choices=[('locataire', 'Locataire'), ('acheteur', 'Acheteur')], default='locataire', max_length=20),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('type_operation', models.CharField(choices=[('location', 'Location'), ('vente', 'Vente')], default='location', max_length=20, verbose_name="Type d'opération")),
                ('date_debut', models.DateField(verbose_name='Date de début du contrat')),
                ('date_fin', models.DateField(verbose_name='Date de fin du contrat')),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20, verbose_name='Périodicité du paiement')),
                ('nombre_periodes', models.IntegerField(help_text='Nombre de paiements prévus sur la durée du contrat', verbose_name='Nombre de périodes du contrat')),
                ('montant_location', models.DecimalField(decimal_places=2, help_text='Montant périodique pour une location, prix total pour une vente', max_digits=10, verbose_name='Montant du loyer/prix de vente')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.beaux', verbose_name='Bien immobilier')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_immobiliere.locataire', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_creation'],
            },
        ),
    ]
