# Generated by Django 5.1.4 on 2025-04-02 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0005_alter_locataire_options_locataire_adresse_employeur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='recu_genere',
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.beaux'),
        ),
        migrations.AlterField(
            model_name='location',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.locataire'),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='montant_location',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='nombre_periodes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='periodicite',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_operation',
            field=models.CharField(choices=[('location', 'Location'), ('vente', 'Vente')], default='location', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('carte', 'Carte bancaire')], max_length=20),
        ),
    ]
