# Generated by Django 5.1.4 on 2025-04-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0006_alter_location_options_remove_paiement_recu_genere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='bien',
        ),
        migrations.AddField(
            model_name='location',
            name='id_beaux',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gestion_immobiliere.beaux'),
        ),
    ]
