# Generated by Django 5.1.4 on 2025-04-05 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0007_remove_location_bien_location_id_beaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaux',
            name='prix',
            field=models.DecimalField(decimal_places=0, help_text='Montant en XOF', max_digits=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.locataire'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id_beaux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gestion_immobiliere.beaux'),
        ),
        migrations.AlterField(
            model_name='location',
            name='montant_location',
            field=models.DecimalField(decimal_places=0, help_text='Montant en XOF', max_digits=12),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=0, help_text='Montant en XOF', max_digits=12),
        ),
    ]
