# Generated by Django 5.1.4 on 2025-04-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0008_alter_beaux_prix_alter_location_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='revenu_mensuel',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant en XOF', max_digits=12, null=True),
        ),
    ]
