# Generated by Django 5.1.4 on 2025-04-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0009_alter_locataire_revenu_mensuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='date_modification',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id_location',
        ),
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='avance',
            field=models.IntegerField(default=0, verbose_name='Montant des avances (XOF)'),
        ),
        migrations.AddField(
            model_name='location',
            name='caution',
            field=models.IntegerField(default=0, verbose_name='Montant de la caution (XOF)'),
        ),
        migrations.AddField(
            model_name='location',
            name='caution_restituee',
            field=models.BooleanField(default=False, verbose_name='Caution restituée'),
        ),
        migrations.AddField(
            model_name='location',
            name='date_resiliation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de résiliation'),
        ),
        migrations.AddField(
            model_name='location',
            name='frais_agence',
            field=models.IntegerField(default=0, verbose_name="Frais d'agence (XOF)"),
        ),
        migrations.AddField(
            model_name='location',
            name='motif_resiliation',
            field=models.TextField(blank=True, verbose_name='Motif de résiliation'),
        ),
        migrations.AddField(
            model_name='location',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('resilié', 'Résilié'), ('terminé', 'Terminé')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='location',
            name='montant_location',
            field=models.IntegerField(verbose_name='Montant de la location/vente (XOF)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='periodicite',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_operation',
            field=models.CharField(choices=[('location', 'Location'), ('vente', 'Vente')], default='location', max_length=20),
        ),
        # Modifications pour le modèle Paiement
        migrations.RenameField(
            model_name='paiement',
            old_name='id_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='commentaire',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='date_modification',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='id_paiement',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='numero_reference',
        ),
        migrations.AddField(
            model_name='paiement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('loyer', 'Loyer'), ('caution', 'Caution'), ('avance', 'Avance'), ('frais_agence', "Frais d'agence"), ('restitution_caution', 'Restitution de caution')], default='loyer', max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.IntegerField(verbose_name='Montant (XOF)'),
        ),
    ]
