# Generated by Django 5.1.4 on 2025-04-06 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0010_auto_20250405_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={},
        ),
        migrations.AlterField(
            model_name='location',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.locataire'),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id_beaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.beaux', verbose_name='Bien immobilier'),
        ),
        migrations.AlterField(
            model_name='location',
            name='nombre_periodes',
            field=models.IntegerField(default=12, verbose_name='Nombre de périodes'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(verbose_name='Date de paiement'),
        ),
    ]
