# Generated by Django 5.1.4 on 2025-04-06 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0012_comptebancaire_rapportfinancier_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='depense',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_immobiliere.transaction'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_immobiliere.transaction'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='depense',
            name='id_propriete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_immobiliere.propriete'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
