# Generated by Django 5.1.4 on 2025-04-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0014_tiers_and_data_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiers',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Tiers', 'verbose_name_plural': 'Tiers'},
        ),
        migrations.AddField(
            model_name='tiers',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
