# Generated by Django 5.2.1 on 2025-05-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_immobiliere", "0015_add_date_modification_to_tiers"),
    ]

    operations = []
